apiVersion: v1
kind: Pod
metadata:
  name: color
  labels:
    name: color
spec:
  containers:
  - name: mbukhari5
    image: mmumshad/simple-webapp-color
    env:
      - name: APP_COLOR
        valueFrom:
          secretKeyRef:
            name: color-secret
            key: APP_COLOR
    ports:
      - containerPort: 8080
