apiVersion: v1
kind: Pod
metadata:
  name: color
  labels:
    name: color
spec:
  containers:
  - name: mbukhari5
    image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: pink
    ports:
      - containerPort: 8080
